name: Accessibility Test

on:
  push:
    branches:
      - main
      - CFA-1-add-css
  pull_request:

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t pa11y-test test/e2e/patty-test

      - name: Run Pa11y tests in Docker container
        run: docker run --rm pa11y-test
