name: Accessibility Test

on:
  push:
    branches:
      - main
      - CFA-1-add-css
  pull_request:

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install puppeteer pa11y fs

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget curl ca-certificates unzip \
            libx11-6 libglib2.0-0 libnss3 libgdk-pixbuf2.0-0 \
            libcups2 libxss1 libasound2 libatk-bridge2.0-0 \
            libgtk-3-0 libgbm-dev

      - name: Run Pa11y tests
        run: node test/e2e/pa11yTest.js
